#ifndef ENUMS_H
#define ENUMS_H
enum Direction { DIR_NORTH, DIR_SOUTH, DIR_EAST, DIR_WEST };
enum LightState { LIGHT_RED, LIGHT_YELLOW, LIGHT_GREEN };
enum VehicleType { TYPE_CIVILIAN, TYPE_AMBULANCE, TYPE_POLICE, TYPE_FIRE_TRUCK };
enum EmergencyType { EMERG_FIRE, EMERG_MEDICAL, EMERG_SECURITY, EMERG_ACCIDENT };
enum VehicleStatus { STATUS_IDLE, STATUS_EN_ROUTE, STATUS_AT_SCENE, STATUS_RETURNING };
#endif
